service_name = "metrics-exporter"
database_url = "postgres://postgres:password@localhost:6543"

[steam]
api_key = ""
polling_interval_seconds = 5
steam_ids = []

[otlp_config]
collector_endpoint = "http://localhost:4317"
protocol = "tonic"
enable_stdout = false
log_level = "info"